package com.beamfield.tectocraft;


import static com.beamfield.tectocraft.TectoCraft.*;
import net.minecraft.block.Block;
import net.minecraft.block.BlockOre;
import net.minecraft.block.material.MapColor;
import net.minecraft.block.material.Material;
import net.minecraft.block.material.MaterialLiquid;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.EnumRarity;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor.ArmorMaterial;
import net.minecraft.item.ItemSeeds;
import net.minecraft.item.ItemStack;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.stats.Achievement;
import net.minecraft.stats.AchievementList;
import net.minecraft.util.WeightedRandomChestContent;
import net.minecraftforge.common.AchievementPage;
import net.minecraftforge.common.ChestGenHooks;
import net.minecraftforge.fluids.Fluid;
import net.minecraftforge.fluids.FluidContainerRegistry;
import net.minecraftforge.fluids.FluidRegistry;
import net.minecraftforge.oredict.OreDictionary;

import com.beamfield.tectocraft.block.BlockBindAcid;
import com.beamfield.tectocraft.block.BlockCotton;
import com.beamfield.tectocraft.block.BlockFluidPipe;
import com.beamfield.tectocraft.block.BlockTectonium;
import com.beamfield.tectocraft.block.BlockTungstenOre;
import com.beamfield.tectocraft.block.ElectricEngine;
import com.beamfield.tectocraft.block.ElectricPipe;
import com.beamfield.tectocraft.block.LiquidTank;
import com.beamfield.tectocraft.block.OilEngine;
import com.beamfield.tectocraft.block.OilPump;
import com.beamfield.tectocraft.block.TectoBlock;
import com.beamfield.tectocraft.block.TectonicCrafter;
import com.beamfield.tectocraft.block.TectonicOven;
import com.beamfield.tectocraft.block.TectonicSmasher;
import com.beamfield.tectocraft.block.flashLight0;
import com.beamfield.tectocraft.configs.TectoConfigs;
import com.beamfield.tectocraft.enchantment.AutoSmelt;
import com.beamfield.tectocraft.enchantment.OreFragments;
import com.beamfield.tectocraft.handler.OnSmeltEvent;
import com.beamfield.tectocraft.handler.TectoCraftingManager;
import com.beamfield.tectocraft.items.BankNote;
import com.beamfield.tectocraft.items.BindAcidBucket;
import com.beamfield.tectocraft.items.ItemRainbow;
import com.beamfield.tectocraft.items.Multitool;
import com.beamfield.tectocraft.items.DeathNote;
import com.beamfield.tectocraft.items.EnderRemote;
import com.beamfield.tectocraft.items.EnhancedEnderPearl;
import com.beamfield.tectocraft.items.FeedOMatic;
import com.beamfield.tectocraft.items.Iphone6;
import com.beamfield.tectocraft.items.ItemAcidRod;
import com.beamfield.tectocraft.items.ItemCalculator;
import com.beamfield.tectocraft.items.ItemFlashLight;
import com.beamfield.tectocraft.items.ItemNethersBane;
import com.beamfield.tectocraft.items.ItemPogoStick;
import com.beamfield.tectocraft.items.ItemTectoMatrix;
import com.beamfield.tectocraft.items.ItemTectonium;
import com.beamfield.tectocraft.items.ItemTectoniumArmor;
import com.beamfield.tectocraft.items.ItemTectoniumAxe;
import com.beamfield.tectocraft.items.ItemTectoniumHoe;
import com.beamfield.tectocraft.items.ItemTectoniumPickaxe;
import com.beamfield.tectocraft.items.ItemTectoniumSpade;
import com.beamfield.tectocraft.items.ItemTectoniumSword;
import com.beamfield.tectocraft.items.Jetpack;
import com.beamfield.tectocraft.items.MegaMagnet;
import com.beamfield.tectocraft.items.Minigun;
import com.beamfield.tectocraft.items.RecipeBook;
import com.beamfield.tectocraft.items.TectoItem;
import com.beamfield.tectocraft.items.UpgradeChipCalc;
import com.beamfield.tectocraft.items.Wrench;
import com.beamfield.tectocraft.reference.Reference;
import com.beamfield.tectocraft.tileentity.TileEntityElectricEngine;
import com.beamfield.tectocraft.tileentity.TileEntityElectricPipe;
import com.beamfield.tectocraft.tileentity.TileEntityFluidPipe;
import com.beamfield.tectocraft.tileentity.TileEntityLiquidTank;
import com.beamfield.tectocraft.tileentity.TileEntityOilEngine;
import com.beamfield.tectocraft.tileentity.TileEntityOilPump;
import com.beamfield.tectocraft.tileentity.TileEntityTectonicOven;
import com.beamfield.tectocraft.tileentity.TileEntityTectonicSmasher;
import com.beamfield.tectocraft.worldgen.TungstenWorldGen;

import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

public class ModRegistry {
	public static void init(){	
		if(TectoConfigs.initOreDict){
			OreDictionary.registerOre("oreTungsten", TectoCraft.tungsten_ore);
			OreDictionary.registerOre("dustTungsten", TectoCraft.tungsten_dust);
			OreDictionary.registerOre("ingotTungsten", TectoCraft.tungsten_ingot);
		}
		if(!TectoConfigs.hardTectoniumCraftingRecipe){
			GameRegistry.addShapelessRecipe(new ItemStack(TectoCraft.tectonium_block), Items.ender_pearl, Item.getItemFromBlock(Blocks.iron_block), Items.blaze_powder, Item.getItemFromBlock(Blocks.dirt));
		}else{
			GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.acidRod, 1, 0), new Object[]{"EDB", " S ", " S ", 'E', Items.ender_pearl, 'D', Blocks.dirt, 'B', Items.blaze_powder, 'S', Items.stick});
			ItemStack infinity_matrix = new ItemStack(TectoCraft.tectoMatrix, 1);
			infinity_matrix.setItemDamage(1);
			GameRegistry.addShapelessRecipe(new ItemStack(TectoCraft.acidRod, 1, 1), TectoCraft.acidRod, infinity_matrix);
			ItemStack power_matrix = new ItemStack(TectoCraft.tectoMatrix, 1);
			power_matrix.setItemDamage(2);
			ItemStack acidRodInf = new ItemStack(TectoCraft.acidRod, 1);
			acidRodInf.setItemDamage(1);
			ItemStack acidRodPow = new ItemStack(TectoCraft.acidRod, 2);
			acidRodPow.setItemDamage(2);
			//GameRegistry.addShapelessRecipe(new ItemStack(TectoCraft.acidRod, 1, 2), TectoCraft.acidRod, power_matrix);
			//GameRegistry.addShapelessRecipe(new ItemStack(TectoCraft.acidRod, 1, 3), acidRodInf, power_matrix);
			//GameRegistry.addShapelessRecipe(new ItemStack(TectoCraft.acidRod, 1, 3), acidRodPow, infinity_matrix);
		}
	}
	public static void preInit(){
		//Ingots
		ingotLead = new Item().setTextureName(Reference.MODID+":lead_ingot").setCreativeTab(tabTectoCraft).setUnlocalizedName("ingotLead");
		GameRegistry.registerItem(ingotLead, "ingotLead");
		LanguageRegistry.addName(ingotLead, "Lead ingot");
		ingotSteel = new Item().setTextureName(Reference.MODID+":steel_ingot").setCreativeTab(tabTectoCraft).setUnlocalizedName("ingotSteel");
		GameRegistry.registerItem(ingotSteel, "ingotSteel");
		LanguageRegistry.addName(ingotSteel, "Steel ingot");
		ingotSilver = new Item().setTextureName(Reference.MODID+":silver_ingot").setCreativeTab(tabTectoCraft).setUnlocalizedName("ingotSilver");
		GameRegistry.registerItem(ingotSilver, "ingotSilver");
		LanguageRegistry.addName(ingotSilver, "Silver ingot");
		ingotNickel = new Item().setTextureName(Reference.MODID+":nickel_ingot").setCreativeTab(tabTectoCraft).setUnlocalizedName("ingotNickel");
		GameRegistry.registerItem(ingotNickel, "ingotNickel");
		LanguageRegistry.addName(ingotNickel, "Nickel ingot");
		ingotCopper = new Item().setTextureName(Reference.MODID+":copper_ingot").setCreativeTab(tabTectoCraft).setUnlocalizedName("ingotCopper");
		GameRegistry.registerItem(ingotCopper, "ingotCopper");
		LanguageRegistry.addName(ingotCopper, "Copper ingot");
		ingotBronze = new Item().setTextureName(Reference.MODID+":bronze_ingot").setCreativeTab(tabTectoCraft).setUnlocalizedName("ingotBronze");
		GameRegistry.registerItem(ingotBronze, "ingotBronze");
		LanguageRegistry.addName(ingotBronze, "Bronze ingot");
		ingotAluminum = new Item().setTextureName(Reference.MODID+":aluminum_ingot").setCreativeTab(tabTectoCraft).setUnlocalizedName("ingotAluminum");
		GameRegistry.registerItem(ingotAluminum, "ingotAluminum");
		LanguageRegistry.addName(ingotAluminum, "Aluminum ingot");
		ingotTin = new Item().setTextureName(Reference.MODID+":tin_ingot").setCreativeTab(tabTectoCraft).setUnlocalizedName("ingotTin");
		GameRegistry.registerItem(ingotTin, "ingotTin");
		LanguageRegistry.addName(ingotTin, "Tin ingot");
		
		OreDictionary.registerOre("ingotLead", ingotLead);
		OreDictionary.registerOre("ingotSteel", ingotSteel);
		OreDictionary.registerOre("ingotSilver", ingotSilver);
		OreDictionary.registerOre("ingotNickel", ingotNickel);
		OreDictionary.registerOre("ingotCopper", ingotCopper);
		OreDictionary.registerOre("ingotBronze", ingotBronze);
		OreDictionary.registerOre("ingotAluminum", ingotAluminum);
		OreDictionary.registerOre("ingotTin", ingotTin);
		//Dusts:
		dustSteel = new Item().setTextureName(Reference.MODID+":steel_dust").setCreativeTab(tabTectoCraft).setUnlocalizedName("dustSteel");
		GameRegistry.registerItem(dustSteel, "dustSteel");
		LanguageRegistry.addName(dustSteel, "Steel Dust");
		dustBronze = new Item().setTextureName(Reference.MODID+":bronze_dust").setCreativeTab(tabTectoCraft).setUnlocalizedName("dustBronze");
		GameRegistry.registerItem(dustBronze, "dustBronze");
		LanguageRegistry.addName(dustBronze, "Bronze Dust");
		dustCopper = new Item().setTextureName(Reference.MODID+":copper_dust").setCreativeTab(tabTectoCraft).setUnlocalizedName("dustCopper");
		GameRegistry.registerItem(dustCopper, "dustCopper");
		LanguageRegistry.addName(dustCopper, "Copper Dust");
		dustTin = new Item().setTextureName(Reference.MODID+":tin_dust").setCreativeTab(tabTectoCraft).setUnlocalizedName("dustTin");
		GameRegistry.registerItem(dustTin, "dustTin");
		LanguageRegistry.addName(dustTin, "Tin Dust");
		dustLead = new Item().setTextureName(Reference.MODID+":lead_dust").setCreativeTab(tabTectoCraft).setUnlocalizedName("dustLead");
		GameRegistry.registerItem(dustLead, "dustLead");
		LanguageRegistry.addName(dustLead, "Lead Dust");
		dustAluminum = new Item().setTextureName(Reference.MODID+":aluminum_dust").setCreativeTab(tabTectoCraft).setUnlocalizedName("dustAluminum");
		GameRegistry.registerItem(dustAluminum, "dustAluminum");
		LanguageRegistry.addName(dustAluminum, "Aluminum Dust");
		dustNickel = new Item().setTextureName(Reference.MODID+":nickel_dust").setCreativeTab(tabTectoCraft).setUnlocalizedName("dustNickel");
		GameRegistry.registerItem(dustNickel, "dustNickel");
		LanguageRegistry.addName(dustNickel, "Nickel Dust");
		dustIron = new Item().setTextureName(Reference.MODID+":iron_dust").setCreativeTab(tabTectoCraft).setUnlocalizedName("dustIron");
		GameRegistry.registerItem(dustIron, "dustIron");
		LanguageRegistry.addName(dustIron, "Iron Dust");
		dustGold = new Item().setTextureName(Reference.MODID+":gold_dust").setCreativeTab(tabTectoCraft).setUnlocalizedName("dustGold");
		GameRegistry.registerItem(dustGold, "dustGold");
		LanguageRegistry.addName(dustGold, "Gold Dust");
		dustSilver = new Item().setTextureName(Reference.MODID+":silver_dust").setCreativeTab(tabTectoCraft).setUnlocalizedName("dustSilver");
		GameRegistry.registerItem(dustSilver, "dustSilver");
		LanguageRegistry.addName(dustSilver, "Silver Dust");
		
		OreDictionary.registerOre("dustSteel", dustSteel);
		OreDictionary.registerOre("dustCopper", dustCopper);
		OreDictionary.registerOre("dustTin", dustTin);
		OreDictionary.registerOre("dustLead", dustLead);
		OreDictionary.registerOre("ingotBronze", ingotBronze);
		OreDictionary.registerOre("dustAluminum", dustAluminum);
		OreDictionary.registerOre("dustNickel", dustNickel);
		OreDictionary.registerOre("dustIron", dustIron);
		OreDictionary.registerOre("dustGold", dustGold);
		OreDictionary.registerOre("dustSilver", dustSilver);
		//Items:
		feedomatic = new FeedOMatic().setTextureName(Reference.MODID+":feedomatic").setUnlocalizedName("feedomatic");
		GameRegistry.registerItem(feedomatic, "feedomatic");
		LanguageRegistry.addName(feedomatic, "Feed-O-Matic");
		iphone6 = new Iphone6().setUnlocalizedName("iphone6").setCreativeTab(tabTectoCraft).setFull3D().setMaxStackSize(1);
		GameRegistry.registerItem(iphone6, "iphone6");
		LanguageRegistry.addName(iphone6, "iPhone");
		chunkLapis = new Item().setUnlocalizedName("lapis_chunk").setCreativeTab(tabTectoCraft).setTextureName(Reference.MODID+":lapis_chunk");
		GameRegistry.registerItem(chunkLapis, "chunkLapis");
		LanguageRegistry.addName(chunkLapis, "Lapis Lazuli Ore Chunk");
		chunkRedstone = new Item().setUnlocalizedName("redstone_chunk").setCreativeTab(tabTectoCraft).setTextureName(Reference.MODID+":redstone_chunk");
		GameRegistry.registerItem(chunkRedstone, "chunkRedstone");
		LanguageRegistry.addName(chunkRedstone, "Redstone Ore Chunk");
		chunkLead = new Item().setUnlocalizedName("lead_chunk").setCreativeTab(tabTectoCraft).setTextureName(Reference.MODID+":lead_chunk");
		GameRegistry.registerItem(chunkLead, "chunkLead");
		LanguageRegistry.addName(chunkLead, "Lead Ore Chunk");
		chunkNickel = new Item().setUnlocalizedName("nickel_chunk").setCreativeTab(tabTectoCraft).setTextureName(Reference.MODID+":nickel_chunk");
		GameRegistry.registerItem(chunkNickel, "chunkNickel");
		LanguageRegistry.addName(chunkNickel, "Nickel Ore Chunk");
		chunkTin = new Item().setUnlocalizedName("tin_chunk").setCreativeTab(tabTectoCraft).setTextureName(Reference.MODID+":tin_chunk");
		GameRegistry.registerItem(chunkTin, "chunkTin");
		LanguageRegistry.addName(chunkTin, "Tin Ore Chunk");
		chunkAluminum = new Item().setUnlocalizedName("aluminum_chunk").setCreativeTab(tabTectoCraft).setTextureName(Reference.MODID+":aluminum_chunk");
		GameRegistry.registerItem(chunkAluminum, "chunkAluminum");
		LanguageRegistry.addName(chunkAluminum, "Aluminum Ore Chunk");
		chunkSilver = new Item().setUnlocalizedName("silver_chunk").setCreativeTab(tabTectoCraft).setTextureName(Reference.MODID+":silver_chunk");
		GameRegistry.registerItem(chunkSilver, "chunkSilver");
		LanguageRegistry.addName(chunkSilver, "Silver Ore Chunk");
		chunkIron = new Item().setUnlocalizedName("iron_chunk").setCreativeTab(tabTectoCraft).setTextureName(Reference.MODID+":iron_chunk");
		GameRegistry.registerItem(chunkIron, "chunkIron");
		LanguageRegistry.addName(chunkIron, "Iron Ore Chunk");
		chunkGold = new Item().setUnlocalizedName("gold_chunk").setCreativeTab(tabTectoCraft).setTextureName(Reference.MODID+":gold_chunk");
		GameRegistry.registerItem(chunkGold, "chunkGold");
		LanguageRegistry.addName(chunkGold, "Gold Ore Chunk");
		chunkCopper = new Item().setUnlocalizedName("copper_chunk").setCreativeTab(tabTectoCraft).setTextureName(Reference.MODID+":copper_chunk");
		GameRegistry.registerItem(chunkCopper, "chunkCopper");
		LanguageRegistry.addName(chunkCopper, "Copper Ore Chunk");
		bankNote = new BankNote().setUnlocalizedName("bankNote").setCreativeTab(tabTectoCraft).setMaxStackSize(64).setTextureName(Reference.MODID+":banknote");
		GameRegistry.registerItem(bankNote, "bankNote");
		LanguageRegistry.addName(bankNote, "Bank Note");
		cottonFabric = new Item().setTextureName(Reference.MODID+":cotton_fabric_white").setUnlocalizedName("cottonFabric").setCreativeTab(tabTectoCraft);
		GameRegistry.registerItem(cottonFabric, "cottonFabric");
		LanguageRegistry.addName(cottonFabric, "Cotton Fabric");
		pogoStick = new ItemPogoStick().setTextureName(Reference.MODID+":pogostick").setUnlocalizedName("pogostick").setCreativeTab(tabTectoCraft);
		GameRegistry.registerItem(pogoStick, "pogoStick");
		LanguageRegistry.addName(pogoStick, "Pogostick");
		deathNote = new DeathNote().setTextureName(Reference.MODID+":deathNote").setUnlocalizedName("deathNote").setCreativeTab(tabTectoCraft);
		GameRegistry.registerItem(deathNote, "deathNote");
		LanguageRegistry.addName(deathNote, "Death Note");
		upgradeChipCalc = new UpgradeChipCalc().setTextureName(Reference.MODID+":upgradeChip").setUnlocalizedName("upgradeChip").setCreativeTab(tabTectoCraft);
		GameRegistry.registerItem(upgradeChipCalc, "upgradeChipCalc");
		LanguageRegistry.addName(upgradeChipCalc, "Upgrade Chip");
		calculator = new ItemCalculator().setTextureName(Reference.MODID+":calculator").setUnlocalizedName("itemCalculator").setCreativeTab(tabTectoCraft).setMaxStackSize(1);
		GameRegistry.registerItem(calculator, "calculator");
		LanguageRegistry.addName(calculator, "Calculator");
		hammer = new Wrench().setTextureName(Reference.MODID+":hammer").setUnlocalizedName("hammer").setCreativeTab(tabTectoCraft).setFull3D();
		GameRegistry.registerItem(hammer, "hammer");
		LanguageRegistry.addName(hammer, "Hammer");
		tectoRecipeBook = new RecipeBook().setTextureName("book_written").setUnlocalizedName("recipebook");
		GameRegistry.registerItem(tectoRecipeBook, "tectoRecipeBook");
		LanguageRegistry.addName(tectoRecipeBook, "Tectonic Crafter Recipe Book");
		rainbow = new ItemRainbow().setTextureName(Reference.MODID+":lucky").setUnlocalizedName("luckyStar").setCreativeTab(tabTectoCraft);
		GameRegistry.registerItem(rainbow, "rainbow");
		LanguageRegistry.addName(rainbow, "Star of the Luck");
		megaMagnet = new MegaMagnet().setTextureName(Reference.MODID+":megamagnet").setUnlocalizedName("megamagnet");
		GameRegistry.registerItem(megaMagnet, "megaMagnet");
		LanguageRegistry.addName(megaMagnet, "Mega Magnet");
		flashLight = new ItemFlashLight().setTextureName(Reference.MODID+":flashlight_off").setUnlocalizedName("flashLight");
		GameRegistry.registerItem(flashLight, "flashLight");
		LanguageRegistry.addName(flashLight, "Flashlight");
		tectonium = new ItemTectonium().setTextureName(Reference.MODID + ":tectonium").setUnlocalizedName("tectonium");
		GameRegistry.registerItem(tectonium, "tectonium");
		LanguageRegistry.addName(tectonium, "Tectonium Ingot");
		acidRod = new ItemAcidRod().setTextureName(Reference.MODID + ":acidRod").setUnlocalizedName("acidRod");
		GameRegistry.registerItem(acidRod, "acidRod");
		LanguageRegistry.addName(acidRod, "Acid Rod");
		tectoMatrix = new ItemTectoMatrix().setNoRepair().setUnlocalizedName("tectoMatrix").setHasSubtypes(true).setTextureName(Reference.MODID+":matrix");
		GameRegistry.registerItem(tectoMatrix, "tectoMatrix");
		LanguageRegistry.addName(tectoMatrix, "Tectonic Matrix");
		tungsten_dust = new TectoItem().setUnlocalizedName("tungsten_dust").setTextureName(Reference.MODID+":tungsten_dust");
		GameRegistry.registerItem(tungsten_dust, "tungsten_dust");
		LanguageRegistry.addName(tungsten_dust, "Tungsten Dust");
		tungsten_ingot = new TectoItem().setUnlocalizedName("tungsten_ingot").setTextureName(Reference.MODID+":tungsten_ingot");
		GameRegistry.registerItem(tungsten_ingot, "tungsten_ingot");
		LanguageRegistry.addName(tungsten_ingot, "Tungsten Ingot");
		rocket_thruster = new TectoItem().setUnlocalizedName("rocket_thruster").setTextureName(Reference.MODID+":rocket_thruster");
		GameRegistry.registerItem(rocket_thruster, "rocket_thruster");
		LanguageRegistry.addName(rocket_thruster, "Rocket Thruster");
		rocket_sealing = new TectoItem().setUnlocalizedName("rocket_sealing").setTextureName(Reference.MODID+":rocket_sealing");
		GameRegistry.registerItem(rocket_sealing, "rocket_sealing");
		LanguageRegistry.addName(rocket_sealing, "Rocket Sealing");
		rocket_casing = new TectoItem().setUnlocalizedName("rocket_casing").setTextureName(Reference.MODID+":rocket_casing");
		GameRegistry.registerItem(rocket_casing, "rocket_casing");
		LanguageRegistry.addName(rocket_casing, "Rocket Casing");
		rocket_fuel = new TectoItem().setUnlocalizedName("rocket_fuel").setTextureName(Reference.MODID+":rocket_fuel").setMaxStackSize(16);
		GameRegistry.registerItem(rocket_fuel, "rocket_fuel");
		LanguageRegistry.addName(rocket_fuel, "Rocket Fuel");
		rocket = new TectoItem().setUnlocalizedName("rocket").setTextureName(Reference.MODID+":rocket").setMaxStackSize(1);
		GameRegistry.registerItem(rocket, "rocket");
		LanguageRegistry.addName(rocket, "Solid Fueled Rocket");
		enderRemote = new EnderRemote().setUnlocalizedName("enderRemote");
		GameRegistry.registerItem(enderRemote, "enderRemote");
		LanguageRegistry.addName(enderRemote, "Ender Remote");
		LED = new TectoItem().setUnlocalizedName("led").setTextureName(Reference.MODID+":led");
		GameRegistry.registerItem(LED, "LED");
		LanguageRegistry.addName(LED, "LED");
		jetpack = new Jetpack(ArmorMaterial.IRON, TectoCraft.armorIDjetpack, 1).setUnlocalizedName("jetpack").setCreativeTab(tabTectoCraft).setTextureName(Reference.MODID+":jetpack");
		GameRegistry.registerItem(jetpack, "jetpack");
		LanguageRegistry.addName(jetpack, "Jetpack");
		enhancedEnderPearl = new EnhancedEnderPearl().setUnlocalizedName("enhancedEnderPearl").setTextureName(Reference.MODID+":enhanced_ender_pearl");
		GameRegistry.registerItem(enhancedEnderPearl, "enhancedEnderPearl");
		LanguageRegistry.addName(enhancedEnderPearl, "Enhanced Ender Pearl");
		minigun = new Minigun().setFull3D().setUnlocalizedName("minigun").setCreativeTab(tabTectoCraft);
		GameRegistry.registerItem(minigun, "minigun");
		LanguageRegistry.addName(minigun, "Minigun");
		//Armors:
		tectoniumHelmet = new ItemTectoniumArmor(TectoCraft.TectoniumMaterialArmor, TectoCraft.armorIDtectoniumHelmet, 0).setUnlocalizedName("itemTectoniumHelmet").setCreativeTab(tabTectoCraft).setTextureName(Reference.MODID+":tectonium_helmet");
		tectoniumChestplate = new ItemTectoniumArmor(TectoCraft.TectoniumMaterialArmor, TectoCraft.armorIDtectoniumChestplate, 1).setUnlocalizedName("tectoniumChestplate").setCreativeTab(tabTectoCraft).setTextureName(Reference.MODID+":tectonium_chestplate");
		tectoniumLeggings = new ItemTectoniumArmor(TectoCraft.TectoniumMaterialArmor, TectoCraft.armorIDtectoniumLeggings, 2).setUnlocalizedName("tectoniumLeggings").setCreativeTab(tabTectoCraft).setTextureName(Reference.MODID+":tectonium_leggings");
		tectoniumBoots = new ItemTectoniumArmor(TectoCraft.TectoniumMaterialArmor, TectoCraft.armorIDtectoniumBoots, 3).setUnlocalizedName("itemTectoniumBoots").setCreativeTab(tabTectoCraft).setTextureName(Reference.MODID+":tectonium_boots");
		tectoBoots = new ItemTectoniumArmor(TectoCraft.TectoniumMaterialArmor, TectoCraft.armorIDtectoBoots, 3).setUnlocalizedName("itemTectoBoots").setCreativeTab(tabTectoCraft);
		//Tools:
		tectoniumSword = new ItemTectoniumSword(TectoCraft.TectoniumMaterial).setUnlocalizedName("itemTectoniumSword").setCreativeTab(tabTectoCraft).setTextureName(Reference.MODID+":tectonium_sword");
		tectoniumPickaxe = new ItemTectoniumPickaxe(TectoCraft.TectoniumMaterial).setUnlocalizedName("itemTectoniumPickaxe").setCreativeTab(tabTectoCraft).setTextureName(Reference.MODID+":tectonium_pickaxe");
		tectoniumSpade = new ItemTectoniumSpade(TectoCraft.TectoniumMaterial).setUnlocalizedName("itemTectoniumSpade").setCreativeTab(tabTectoCraft).setTextureName(Reference.MODID+":tectonium_shovel");
		tectoniumAxe = new ItemTectoniumAxe(TectoCraft.TectoniumMaterial).setUnlocalizedName("itemTectoniumAxe").setCreativeTab(tabTectoCraft).setTextureName(Reference.MODID+":tectonium_axe");
		tectoniumHoe = new ItemTectoniumHoe(TectoCraft.TectoniumMaterial).setUnlocalizedName("itemTectoniumHoe").setCreativeTab(tabTectoCraft).setTextureName(Reference.MODID+":tectonium_hoe");
		nethersBane = new ItemNethersBane(TectoCraft.NethersBaneMaterial).setUnlocalizedName("itemNethersBane").setCreativeTab(tabTectoCraft).setFull3D();
		tectonicMultitool = new Multitool(25F, TectoCraft.MultitoolMaterial, null).setUnlocalizedName("tectonicMultitool").setCreativeTab(tabTectoCraft).setFull3D();
		GameRegistry.registerItem(tectonicMultitool, "tectonicMultitool");
		LanguageRegistry.addName(tectonicMultitool, "Tectonic Mace");
		GameRegistry.registerItem(tectoniumSword, "tectoniumSword");
		LanguageRegistry.addName(tectoniumSword, "Tectonium Sword");
		GameRegistry.registerItem(nethersBane, "nethersBane");
		LanguageRegistry.addName(nethersBane, "Nether's bane");
		GameRegistry.registerItem(tectoniumPickaxe, "tectoniumPickaxe");
		LanguageRegistry.addName(tectoniumPickaxe, "Tectonium Pickaxe");
		GameRegistry.registerItem(tectoniumSpade, "tectoniumSpade");
		LanguageRegistry.addName(tectoniumSpade, "Tectonium Shovel");
		GameRegistry.registerItem(tectoniumAxe, "tectoniumAxe");
		LanguageRegistry.addName(tectoniumAxe, "Tectonium Axe");
		GameRegistry.registerItem(tectoniumHoe, "tectoniumHoe");
		LanguageRegistry.addName(tectoniumHoe, "Tectonium Hoe");
		GameRegistry.registerItem(tectoniumHelmet, "tectoniumHelmet");
		LanguageRegistry.addName(tectoniumHelmet, "Tectonium Helmet");
		GameRegistry.registerItem(tectoniumChestplate, "tectoniumChestplate");
		LanguageRegistry.addName(tectoniumChestplate, "Tectonium Chestplate");
		GameRegistry.registerItem(tectoniumLeggings, "tectoniumLeggings");
		LanguageRegistry.addName(tectoniumLeggings, "Tectonium Leggings");
		GameRegistry.registerItem(tectoniumBoots, "tectoniumBoots");
		LanguageRegistry.addName(tectoniumBoots, "Tectonium Boots");
		//Blocks:
		oilPump = new OilPump(Material.iron).setHardness(3F).setResistance(10F).setStepSound(Block.soundTypeMetal).setBlockName("oilPump").setCreativeTab(tabTectoCraft);
		GameRegistry.registerBlock(oilPump, "oilPump");
		LanguageRegistry.addName(oilPump, "Oil Pump");
		
		cottonCrop = new BlockCotton().setBlockName("cottonCrop").setStepSound(Block.soundTypeGrass);
		GameRegistry.registerBlock(cottonCrop, "cottonCrop");
		LanguageRegistry.addName(cottonCrop, "Cotton Crop");
		cottonItem = new ItemSeeds(TectoCraft.cottonCrop, Blocks.farmland).setTextureName(Reference.MODID+":cotton_plant").setUnlocalizedName("cottonItem").setCreativeTab(tabTectoCraft);
		GameRegistry.registerItem(cottonItem, "cottonItem");
		LanguageRegistry.addName(cottonItem, "Cotton");
		electricPipe = new ElectricPipe(Material.iron).setHardness(3F).setResistance(10F).setStepSound(Block.soundTypeMetal).setBlockName("electricPipe").setCreativeTab(tabTectoCraft);
		GameRegistry.registerBlock(electricPipe, "electricPipe");
		LanguageRegistry.addName(electricPipe, "Electric Cable");
		liquidTank = new LiquidTank(Material.iron).setHardness(3F).setResistance(10F).setStepSound(Block.soundTypeMetal).setBlockName("liquidTank").setCreativeTab(tabTectoCraft);
		GameRegistry.registerBlock(liquidTank, "liquidTank");
		LanguageRegistry.addName(liquidTank, "Liquid Tank");
		fluidPipe = new BlockFluidPipe().setHardness(3F).setResistance(10F).setStepSound(Block.soundTypeMetal).setBlockName("fluidPipe").setCreativeTab(tabTectoCraft);
		GameRegistry.registerBlock(fluidPipe, "fluidPipe");
		LanguageRegistry.addName(fluidPipe, "Fluid Pipe");
		electricEngine = new ElectricEngine(Material.iron).setHardness(3F).setResistance(10F).setStepSound(Block.soundTypeMetal).setBlockName("electricEngine").setCreativeTab(tabTectoCraft);
		GameRegistry.registerBlock(electricEngine, "electricEngine");
		LanguageRegistry.addName(electricEngine, "Electric Engine");
		oilEngine = new OilEngine(Material.iron).setHardness(3F).setResistance(10F).setStepSound(Block.soundTypeMetal).setBlockName("oilEngine").setCreativeTab(tabTectoCraft);
		GameRegistry.registerBlock(oilEngine, "oilEngine");
		LanguageRegistry.addName(oilEngine, "Oil Engine");
		tectonium_block = new BlockTectonium(Material.iron).setBlockTextureName(Reference.MODID+":tectonium_block").setLightLevel(5.0F).setHardness(3F).setResistance(10F).setStepSound(Block.soundTypeMetal).setBlockName("tectoniumblock");
		GameRegistry.registerBlock(tectonium_block, "tectonium_block");
		LanguageRegistry.addName(tectonium_block, "Tectonium Block");
		tectoWall = new TectoBlock(Material.iron).setBlockTextureName(Reference.MODID+":tectowall").setLightLevel(5.0F).setHardness(3F).setResistance(10F).setStepSound(Block.soundTypeMetal).setBlockName("tectoniumWall");
		GameRegistry.registerBlock(tectoWall, "tectoWall");
		LanguageRegistry.addName(tectoWall, "Tectonium Crafter Wall");
		flashLight0 = new flashLight0(Material.air).setBlockName("flashlight0");
		GameRegistry.registerBlock(flashLight0, "flashLight0");
		LanguageRegistry.addName(flashLight0, "Light");
		tungsten_ore = new BlockTungstenOre(Material.rock).setHardness(5F).setResistance(10F).setStepSound(Block.soundTypeStone).setBlockTextureName(Reference.MODID+":tungsten_ore_world").setBlockName("tungstenore");
		GameRegistry.registerBlock(tungsten_ore, "tungsten_ore");
		LanguageRegistry.addName(tungsten_ore, "Tungsten Ore");
		tungsten_block = new TectoBlock(Material.iron).setHardness(5F).setResistance(10F).setStepSound(Block.soundTypeMetal).setBlockTextureName(Reference.MODID+":tungsten_block").setBlockName("tungstenblock");
		GameRegistry.registerBlock(tungsten_block, "tungsten_block");
		LanguageRegistry.addName(tungsten_block, "Tungsten Block");
		tectonic_crafter = new TectonicCrafter(Material.iron).setBlockName("tectocrafter");
		GameRegistry.registerBlock(tectonic_crafter, "tectonic_crafter");
		LanguageRegistry.addName(tectonic_crafter, "Tectonic Crafter");
		tectoOven_idle = new TectonicOven(false).setBlockName("TectoOvenIdle").setCreativeTab(TectoCraft.tabTectoCraft);
		GameRegistry.registerBlock(tectoOven_idle, "tectoOven_idle");
		LanguageRegistry.addName(tectoOven_idle, "Tectonic Oven");
		tectoOven_active = new TectonicOven(true).setBlockName("TectonicOvenActive").setLightLevel(0.625F);
		GameRegistry.registerBlock(tectoOven_active, "tectoOven_active");
		LanguageRegistry.addName(tectoOven_active, "Tectonic Oven");
		blockSmasherIdle = new TectonicSmasher(false).setBlockName("blockSmasherIdle").setLightLevel(0.625F).setHardness(3.7F).setCreativeTab(tabTectoCraft);
		GameRegistry.registerBlock(blockSmasherIdle, "blockSmasherIdle");
		LanguageRegistry.addName(blockSmasherIdle, "Tectonic Smasher");
		blockSmasherActive = new TectonicSmasher(true).setBlockName("blockSmasherActive").setLightLevel(0.625F).setHardness(3.7F);
		GameRegistry.registerBlock(blockSmasherActive, "blockSmasherActive");
		LanguageRegistry.addName(blockSmasherActive, "Tectonic Smasher");
		oreAluminum = new BlockOre().setBlockName("oreAluminum").setBlockTextureName(Reference.MODID+":ore_aluminum").setCreativeTab(tabTectoCraft).setStepSound(Block.soundTypeStone).setHardness(2F).setResistance(2F);
		GameRegistry.registerBlock(oreAluminum, "oreAluminum");
		LanguageRegistry.addName(oreAluminum, "Aluminum Ore");
		OreDictionary.registerOre("oreAluminum", oreAluminum);
		oreCopper = new BlockOre().setBlockName("oreCopper").setBlockTextureName(Reference.MODID+":ore_copper").setCreativeTab(tabTectoCraft).setStepSound(Block.soundTypeStone).setHardness(2F).setResistance(2F);
		GameRegistry.registerBlock(oreCopper, "oreCopper");
		LanguageRegistry.addName(oreCopper, "Copper Ore");
		OreDictionary.registerOre("oreCopper", oreCopper);
		oreLead = new BlockOre().setBlockName("oreLead").setBlockTextureName(Reference.MODID+":ore_lead").setCreativeTab(tabTectoCraft).setStepSound(Block.soundTypeStone).setHardness(2F).setResistance(2F);
		GameRegistry.registerBlock(oreLead, "oreLead");
		LanguageRegistry.addName(oreLead, "Lead Ore");
		OreDictionary.registerOre("oreLead", oreLead);
		oreNickel = new BlockOre().setBlockName("oreNickel").setBlockTextureName(Reference.MODID+":ore_nickel").setCreativeTab(tabTectoCraft).setStepSound(Block.soundTypeStone).setHardness(2F).setResistance(2F);
		GameRegistry.registerBlock(oreNickel, "oreNickel");
		LanguageRegistry.addName(oreNickel, "Nickel Ore");
		OreDictionary.registerOre("oreAluminum", oreAluminum);
		oreSilver = new BlockOre().setBlockName("oreSilver").setBlockTextureName(Reference.MODID+":ore_silver").setCreativeTab(tabTectoCraft).setStepSound(Block.soundTypeStone).setHardness(2F).setResistance(2F);
		GameRegistry.registerBlock(oreSilver, "oreSilver");
		LanguageRegistry.addName(oreSilver, "Silver Ore");
		OreDictionary.registerOre("oreSilver", oreSilver);
		oreTin = new BlockOre().setBlockName("oreTin").setBlockTextureName(Reference.MODID+":ore_tin").setCreativeTab(tabTectoCraft).setStepSound(Block.soundTypeStone).setHardness(2F).setResistance(2F);
		GameRegistry.registerBlock(oreTin, "oreTin");
		LanguageRegistry.addName(oreTin, "Tin Ore");
		OreDictionary.registerOre("oreTin", oreTin);
		OreDictionary.registerOre("oreCoal", Blocks.coal_ore);
		
		//TileEntity:
		GameRegistry.registerTileEntity(TileEntityTectonicOven.class, "TectonicOven");
		GameRegistry.registerTileEntity(TileEntityElectricEngine.class, "ElectricEngine");
		GameRegistry.registerTileEntity(TileEntityOilEngine.class, "OilEngine");
		GameRegistry.registerTileEntity(TileEntityOilPump.class, "OilPump");
		GameRegistry.registerTileEntity(TileEntityFluidPipe.class, "FluidPipe");
		GameRegistry.registerTileEntity(TileEntityLiquidTank.class, "LiquidTank");
		GameRegistry.registerTileEntity(TileEntityElectricPipe.class, "ElectricPipe");
		GameRegistry.registerTileEntity(TileEntityTectonicSmasher.class, "TectonicSmasher");
		//Enchantment:
		autoSmelt = new AutoSmelt();
		Enchantment.addToBookList(autoSmelt);
		oreFragments = new OreFragments();
		Enchantment.addToBookList(oreFragments);
		//Worldgen:
		GameRegistry.registerWorldGenerator(new TungstenWorldGen(), 1);
		//Achievement:
		achievementHighTemperatures = new Achievement("achievement.turnuptheteat", "tungsten_ingot", 1, -2, TectoCraft.tungsten_ingot, AchievementList.acquireIron).registerStat().setSpecial();
		AchievementPage.registerAchievementPage(new AchievementPage("TectoCraft", new Achievement[]{achievementHighTemperatures}));
		FMLCommonHandler.instance().bus().register(new OnSmeltEvent());
		//Fluids:
				final Material bindAcidMaterial = (new MaterialLiquid(MapColor.grassColor));
				Fluid bindAcid = new Fluid("bindAcid").setDensity(1500).setViscosity(2000).setUnlocalizedName("bindAcid").setRarity(EnumRarity.epic).setGaseous(false).setLuminosity(4); 
				FluidRegistry.registerFluid(bindAcid);
				bindAcidBlock = new BlockBindAcid(bindAcid, bindAcidMaterial).setBlockName("bindAcid");
				GameRegistry.registerBlock(bindAcidBlock, "bindAcid");
				
				bindAcidbucket = new BindAcidBucket(TectoCraft.bindAcidBlock).setTextureName(Reference.MODID+":bucket_bindAcid").setUnlocalizedName("bucket_bindAcid").setContainerItem(Items.bucket).setCreativeTab(tabTectoCraft);
				GameRegistry.registerItem(bindAcidbucket, "bindAcidbucket");
				LanguageRegistry.addName(bindAcidbucket, "Bucket of BindAcid");
				
				FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack(bindAcid.getName(), FluidContainerRegistry.BUCKET_VOLUME), new ItemStack(bindAcidbucket), new ItemStack(Items.bucket));
				
				ChestGenHooks.getInfo(ChestGenHooks.DUNGEON_CHEST).addItem(new WeightedRandomChestContent(TectoCraft.rainbow, 0, 0, 0, 0));
		//Crafting:
		GameRegistry.addShapelessRecipe(new ItemStack(TectoCraft.bindAcidbucket, 1), Items.gunpowder, Items.blaze_powder, Items.redstone, new ItemStack(Items.water_bucket).getItem().setContainerItem(null), new ItemStack(Items.dye, 1, 10));
		GameRegistry.addShapelessRecipe(new ItemStack(TectoCraft.tectonium, 9), Item.getItemFromBlock(tectonium_block));
		GameRegistry.addShapelessRecipe(new ItemStack(TectoCraft.tungsten_ingot, 9), Item.getItemFromBlock(tungsten_block));
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tectonium_block), new Object[]{"TTT", "TTT", "TTT", 'T', TectoCraft.tectonium});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tungsten_block), new Object[]{"TTT", "TTT", "TTT", 'T', TectoCraft.tungsten_ingot});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tectoMatrix, 1, 0), new Object[]{"TGT", "GDG", "TGT", 'T', TectoCraft.tectonium, 'G', Items.gold_ingot, 'D', Items.diamond});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tectoMatrix, 1, 1), new Object[]{"THT", "TMT", "TET", 'T', TectoCraft.tectonium, 'H', Blocks.hopper, 'E', Items.ender_pearl, 'M', new ItemStack(TectoCraft.tectoMatrix, 0).getItem()});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tectoMatrix, 1, 2), new Object[]{"TRT", "RMR", "TRT", 'T', TectoCraft.tectonium, 'R', Blocks.redstone_block, 'M', new ItemStack(TectoCraft.tectoMatrix, 0).getItem()});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tectoMatrix, 1, 3), new Object[]{"RRR", "TMT", "RRR", 'T', TectoCraft.tungsten_block, 'R', Blocks.redstone_block, 'M', new ItemStack(TectoCraft.tectoMatrix, 0).getItem()});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tectonic_crafter, 1), new Object[]{"ICI", "ITI", "III", 'I', Blocks.iron_block, 'C', Blocks.crafting_table, 'T', tectonium_block});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.LED, 1), new Object[]{"PPP", "PTP", "GPG", 'P', Blocks.glass_pane, 'G', Items.gold_nugget, 'T', tungsten_ingot});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.enderRemote, 1), new Object[]{"QLQ", "QBQ", "QEQ", 'B', Blocks.stone_button, 'Q', Items.quartz, 'L', LED, 'E', Items.ender_pearl});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.enhancedEnderPearl, 1), new Object[]{"TTT", "TET", "TTT", 'T', tectonium, 'E', Items.ender_pearl});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.jetpack, 1), new Object[]{"RGR", "LAL", "JPJ", 'J', rocket, 'R', enderRemote, 'G', Items.gold_ingot, 'L', Items.leather, 'P', Items.iron_chestplate});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tectoOven_idle, 1), new Object[]{"ILI", "IFI", "III", 'I', Blocks.iron_block, 'L', LED, 'F', Blocks.furnace});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.flashLight, 1), new Object[]{"IPI", "ILI", "III", 'I', Items.iron_ingot, 'P', Blocks.glass_pane, 'L', LED});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.feedomatic, 1), new Object[]{"  S", " I ", "I  ", 'I', Items.stick, 'S', Items.cooked_beef});
		GameRegistry.addShapelessRecipe(new ItemStack(TectoCraft.rocket_fuel, 4), Items.sugar, Items.gunpowder, Items.blaze_powder, Items.glowstone_dust);		
		GameRegistry.addShapelessRecipe(new ItemStack(TectoCraft.tectoRecipeBook, 1), Items.book, tectonium);
		GameRegistry.addShapelessRecipe(new ItemStack(Blocks.wool, 1), cottonFabric, cottonFabric, cottonFabric, cottonFabric);
		GameRegistry.addShapedRecipe(new ItemStack(bankNote, 1, 0), new Object[]{"PPP", "LNL", "PPP", 'P', Items.paper, 'N', Items.gold_nugget, 'L', (new ItemStack(Items.dye, 1, 10))});
		GameRegistry.addShapelessRecipe(new ItemStack(bankNote, 1, 1), new ItemStack(bankNote, 1, 0), new ItemStack(bankNote, 1, 0));
		GameRegistry.addShapelessRecipe(new ItemStack(bankNote, 1, 2), new ItemStack(bankNote, 1, 1), new ItemStack(bankNote, 1, 1), new ItemStack(bankNote, 1, 0));
		GameRegistry.addShapelessRecipe(new ItemStack(bankNote, 1, 3), new ItemStack(bankNote, 1, 2), new ItemStack(bankNote, 1, 2));
		GameRegistry.addShapelessRecipe(new ItemStack(bankNote, 1, 4), new ItemStack(bankNote, 1, 3), new ItemStack(bankNote, 1, 3));
		GameRegistry.addShapelessRecipe(new ItemStack(bankNote, 1, 5), new ItemStack(bankNote, 1, 4), new ItemStack(bankNote, 1, 4), new ItemStack(bankNote, 1, 3));
		GameRegistry.addShapelessRecipe(new ItemStack(bankNote, 1, 6), new ItemStack(bankNote, 1, 5), new ItemStack(bankNote, 1, 5));
		GameRegistry.addShapedRecipe(new ItemStack(megaMagnet), new Object[]{"TTT", "T T", "R B", 'T', TectoCraft.tungsten_ingot, 'R', Blocks.redstone_block, 'B', TectoCraft.tungsten_block});
		GameRegistry.addShapedRecipe(new ItemStack(tectoWall, 4), new Object[]{"TTT", "TIT", "TTT", 'T', TectoCraft.tungsten_ingot, 'I', Blocks.iron_block});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.deathNote), new Object[]{"SNS", "WEW", "SWS", 'S', Blocks.soul_sand, 'N', Items.nether_star, 'W', (new ItemStack(Items.skull, 1, 1)), 'E', Blocks.diamond_block});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.calculator), new Object[]{"IRI", "TBT", "ICI", 'I', Items.iron_ingot, 'R', Items.redstone, 'T', Items.repeater, 'B', Blocks.stone_button, 'C', Items.comparator});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.minigun), new Object[]{"IIA", "IGI", "BII", 'I', Items.iron_ingot, 'A', Items.arrow, 'G', Items.gunpowder, 'B', Blocks.iron_block});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.hammer), new Object[]{" II", "BSI", " S ", 'I', Items.iron_ingot, 'S', Items.stick, 'B', Blocks.iron_block});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.cottonFabric), new Object[]{"CCC", "CCC", "CCC", 'C', cottonItem});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.blockSmasherIdle), new Object[]{"IPI", "IFI", "III", 'F', Items.flint, 'I', Blocks.iron_block, 'P', Blocks.piston});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.pogoStick), new Object[]{"ISI", " S ", " P ", 'S', Items.stick, 'I', Items.iron_ingot, 'P', Blocks.piston});
		  //SubCrafting:Tools
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tectoniumSword), new Object[]{"T  ", "T  ", "S  ", 'T', TectoCraft.tectonium, 'S', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tectoniumSword), new Object[]{" T ", " T ", " S ", 'T', TectoCraft.tectonium, 'S', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tectoniumSword), new Object[]{"  T", "  T", "  S", 'T', TectoCraft.tectonium, 'S', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tectoniumPickaxe), new Object[]{"TTT", " S ", " S ", 'T', TectoCraft.tectonium, 'S', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tectoniumSpade), new Object[]{"T  ", "S  ", "S  ", 'T', TectoCraft.tectonium, 'S', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tectoniumSpade), new Object[]{" T ", " S ", " S ", 'T', TectoCraft.tectonium, 'S', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tectoniumSpade), new Object[]{"  T", "  S", "  S", 'T', TectoCraft.tectonium, 'S', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tectoniumAxe), new Object[]{"TT ", "TS ", " S ", 'T', TectoCraft.tectonium, 'S', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tectoniumAxe), new Object[]{" TT", " ST", " S ", 'T', TectoCraft.tectonium, 'S', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tectoniumHoe), new Object[]{"TT ", " S ", " S ", 'T', TectoCraft.tectonium, 'S', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tectoniumHoe), new Object[]{" TT", " S ", " S ", 'T', TectoCraft.tectonium, 'S', Items.stick});
		  //SubCrafting:Armor
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tectoniumHelmet), new Object[]{"TTT", "T T", "   ", 'T', TectoCraft.tectonium});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tectoniumHelmet), new Object[]{"   ", "TTT", "T T", 'T', TectoCraft.tectonium});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tectoniumChestplate), new Object[]{"T T", "TTT", "TTT", 'T', TectoCraft.tectonium});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tectoniumLeggings), new Object[]{"TTT", "T T", "T T", 'T', TectoCraft.tectonium});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tectoniumBoots), new Object[]{"T T", "T T", "   ", 'T', TectoCraft.tectonium});
		GameRegistry.addShapedRecipe(new ItemStack(TectoCraft.tectoniumBoots), new Object[]{"   ", "T T", "T T", 'T', TectoCraft.tectonium});
		//NBTCrafting:Calculator
		ItemStack calcStack = new ItemStack(calculator, 1);
		calcStack.setTagCompound(new NBTTagCompound());
		NBTTagCompound tags = calcStack.stackTagCompound;
		for(int i = 0; i == 7;i++){
			String[] chipTypes = new String[] {"Plus", "Minus", "Multiply", "Divide", "Decimal", "Hexadecimal", "Block Calculation"};
			tags.setString(chipTypes[i], chipTypes[i]);
			GameRegistry.addShapelessRecipe(calcStack, new Object[]{new ItemStack(upgradeChipCalc, 1, i).getItem()});
		}
		//Smelting:
		GameRegistry.addSmelting(new ItemStack(TectoCraft.tectoMatrix).getItem(), new ItemStack(TectoCraft.tectoMatrix), 0.25F);
		GameRegistry.addSmelting(new ItemStack(TectoCraft.tungsten_dust).getItem(), new ItemStack(TectoCraft.tungsten_ingot), 0.25F);
		
		//ingot smelting:
		GameRegistry.addSmelting(new ItemStack(TectoCraft.dustLead).getItem(), new ItemStack(TectoCraft.ingotLead), 0.15F);
		GameRegistry.addSmelting(new ItemStack(TectoCraft.dustBronze).getItem(), new ItemStack(TectoCraft.ingotBronze), 0.15F);
		GameRegistry.addSmelting(new ItemStack(TectoCraft.dustCopper).getItem(), new ItemStack(TectoCraft.ingotCopper), 0.15F);
		GameRegistry.addSmelting(new ItemStack(TectoCraft.dustTin).getItem(), new ItemStack(TectoCraft.ingotTin), 0.15F);
		GameRegistry.addSmelting(new ItemStack(TectoCraft.dustAluminum).getItem(), new ItemStack(TectoCraft.ingotAluminum), 0.15F);
		GameRegistry.addSmelting(new ItemStack(TectoCraft.dustNickel).getItem(), new ItemStack(TectoCraft.ingotNickel), 0.15F);
		GameRegistry.addSmelting(new ItemStack(TectoCraft.dustIron).getItem(), new ItemStack(Items.iron_ingot), 0.15F);
		GameRegistry.addSmelting(new ItemStack(TectoCraft.dustGold).getItem(), new ItemStack(Items.gold_ingot), 0.15F);
		GameRegistry.addSmelting(new ItemStack(TectoCraft.dustSilver).getItem(), new ItemStack(TectoCraft.ingotSilver), 0.15F);
		GameRegistry.addSmelting(new ItemStack(TectoCraft.dustSteel).getItem(), new ItemStack(TectoCraft.ingotSteel), 0.15F);
		
		GameRegistry.addSmelting(new ItemStack(TectoCraft.oreAluminum).getItem(), new ItemStack(TectoCraft.ingotAluminum), 0.15F);
		GameRegistry.addSmelting(new ItemStack(TectoCraft.oreCopper).getItem(), new ItemStack(TectoCraft.ingotCopper), 0.15F);
		GameRegistry.addSmelting(new ItemStack(TectoCraft.oreLead).getItem(), new ItemStack(TectoCraft.ingotLead), 0.15F);
		GameRegistry.addSmelting(new ItemStack(TectoCraft.oreNickel).getItem(), new ItemStack(TectoCraft.ingotNickel), 0.15F);
		GameRegistry.addSmelting(new ItemStack(TectoCraft.oreSilver).getItem(), new ItemStack(TectoCraft.ingotSilver), 0.15F);
		GameRegistry.addSmelting(new ItemStack(TectoCraft.oreTin).getItem(), new ItemStack(TectoCraft.ingotTin), 0.15F);
		//TectoCrafterRecipes:
		TectoCraftingManager.getInstance().addRecipe(new ItemStack(Items.diamond, 1), new Object[]{ "CCCCC", "CCCCC", "CCCCC", "CCCCC", "CCCCC", 'C', Blocks.coal_block});
		TectoCraftingManager.getInstance().addRecipe(new ItemStack(rocket_thruster, 1), new Object[]{ "  S  ", " TTT ", "T   T", "TLFDT", "T   T", 'T', tungsten_ingot, 'L', LED, 'F', rocket_fuel, 'S', rocket_sealing, 'D', Blocks.tnt});
		TectoCraftingManager.getInstance().addRecipe(new ItemStack(rocket_sealing, 1), new Object[]{ "TTTTT", "IIIII", "QQQQQ", "DDDDD", "CCCCC", 'T', tungsten_ingot, 'I', Items.iron_ingot, 'Q', Items.quartz, 'D', Items.diamond, 'C', Blocks.coal_block});
		TectoCraftingManager.getInstance().addRecipe(new ItemStack(rocket_casing, 1), new Object[]{ "IIIII", "TTTTT", "     ", "TTTTT", "IIIII", 'T', tungsten_ingot, 'I', Items.iron_ingot});
		TectoCraftingManager.getInstance().addRecipe(new ItemStack(rocket, 1), new Object[]{ "  I  ", " CPC ", " CCC ", "CCCCC", " T T ", 'T', rocket_thruster, 'I', Blocks.iron_block, 'P', Blocks.glass_pane, 'C', rocket_casing});
		TectoCraftingManager.getInstance().addRecipe(new ItemStack(nethersBane, 1), new Object[]{ "   DD", "  DDD", " DDD ", "END  ", "SE   ", 'D', Blocks.diamond_block, 'E', Blocks.emerald_block, 'N', Items.nether_star, 'S', Items.stick});
		TectoCraftingManager.getInstance().addRecipe(new ItemStack(tectonicMultitool, 1), new Object[]{ "TTNTT", "TTTTT", "  T  ", "  T  ", "  T  ", 'T', TectoCraft.tungsten_block, 'N', TectoCraft.nethersBane});
		//OreDict:
	}
}

